package com.ipn.mx.siipg.modelo;
// Generated 11/02/2017 08:23:27 PM by Hibernate Tools 4.3.1



/**
 * Formato generated by hbm2java
 */
public class Formato  implements java.io.Serializable {


     private int indicadorId;
     private Indicador indicador;
     private int formato;
     private int idDivisor;
     private int idDividendo;

    public Formato() {
    }

    public Formato(Indicador indicador, int formato, int idDivisor, int idDividendo) {
       this.indicador = indicador;
       this.formato = formato;
       this.idDivisor = idDivisor;
       this.idDividendo = idDividendo;
    }
   
    public int getIndicadorId() {
        return this.indicadorId;
    }
    
    public void setIndicadorId(int indicadorId) {
        this.indicadorId = indicadorId;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public int getFormato() {
        return this.formato;
    }
    
    public void setFormato(int formato) {
        this.formato = formato;
    }
    public int getIdDivisor() {
        return this.idDivisor;
    }
    
    public void setIdDivisor(int idDivisor) {
        this.idDivisor = idDivisor;
    }
    public int getIdDividendo() {
        return this.idDividendo;
    }
    
    public void setIdDividendo(int idDividendo) {
        this.idDividendo = idDividendo;
    }




}


