package com.ipn.mx.siipg.modelo;
// Generated 11/02/2017 08:23:27 PM by Hibernate Tools 4.3.1



/**
 * IndicadorTienePeriodo generated by hbm2java
 */
public class IndicadorTienePeriodo  implements java.io.Serializable {


     private IndicadorTienePeriodoId id;
     private Indicador indicador;
     private Periodo periodo;
     private float resultado;

    public IndicadorTienePeriodo() {
    }

    public IndicadorTienePeriodo(IndicadorTienePeriodoId id, Indicador indicador, Periodo periodo, float resultado) {
       this.id = id;
       this.indicador = indicador;
       this.periodo = periodo;
       this.resultado = resultado;
    }
   
    public IndicadorTienePeriodoId getId() {
        return this.id;
    }
    
    public void setId(IndicadorTienePeriodoId id) {
        this.id = id;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public float getResultado() {
        return this.resultado;
    }
    
    public void setResultado(float resultado) {
        this.resultado = resultado;
    }




}


