package com.ipn.mx.siipg.modelo;
// Generated 11/02/2017 08:23:27 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private Integer id;
     private String periodo;
     private Integer estatus;
     private Set indicadorTienePeriodos = new HashSet(0);
     private Set variablechecks = new HashSet(0);

    public Periodo() {
    }

    public Periodo(String periodo, Integer estatus, Set indicadorTienePeriodos, Set variablechecks) {
       this.periodo = periodo;
       this.estatus = estatus;
       this.indicadorTienePeriodos = indicadorTienePeriodos;
       this.variablechecks = variablechecks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Integer getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }
    public Set getIndicadorTienePeriodos() {
        return this.indicadorTienePeriodos;
    }
    
    public void setIndicadorTienePeriodos(Set indicadorTienePeriodos) {
        this.indicadorTienePeriodos = indicadorTienePeriodos;
    }
    public Set getVariablechecks() {
        return this.variablechecks;
    }
    
    public void setVariablechecks(Set variablechecks) {
        this.variablechecks = variablechecks;
    }




}


