package com.ipn.mx.siipg.modelo;
// Generated 12/12/2016 01:27:14 AM by Hibernate Tools 4.3.1

/**
 * Variablecheck generated by hbm2java
 */
public class Variablecheck implements java.io.Serializable {

    private Integer id;
    private Periodo periodo;
    private Variable variable;
    private String comentario;
    private int estatus;
    private Float valor;
    private boolean noIniciada;

    public Variablecheck() {
    }

    public Variablecheck(Periodo periodo, Variable variable, String comentario, int estatus) {
        this.periodo = periodo;
        this.variable = variable;
        this.comentario = comentario;
        this.estatus = estatus;
    }

    public Variablecheck(Periodo periodo, Variable variable, String comentario, int estatus, Float valor) {
        this.periodo = periodo;
        this.variable = variable;
        this.comentario = comentario;
        this.estatus = estatus;
        this.valor = valor;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Periodo getPeriodo() {
        return this.periodo;
    }

    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }

    public Variable getVariable() {
        return this.variable;
    }

    public void setVariable(Variable variable) {
        this.variable = variable;
    }

    public String getComentario() {
        return this.comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    public int getEstatus() {
        return this.estatus;
    }

    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }

    public Float getValor() {
        return this.valor;
    }

    public void setValor(Float valor) {
        this.valor = valor;
    }

    public boolean isNoIniciada() {
        return noIniciada;
    }

    public void setNoIniciada(boolean noIniciada) {
        this.noIniciada = noIniciada;
    }

}
